# con esta configuracion ponemos un nginx para escalar el servicio cabu
version: '3'
services:
  cabu:
    build: .
    ports:
      - "3000:3000/tcp"
    environment:
      - NODE_ENV=debug
      - PORT=3000
    networks:
      - cabu
# bridge sobre nuestra red localhost para acceder
networks:
  cabu:
    driver: bridge
