apiVersion: v1
kind: Pod
metadata:
  name: nodecustom
  labels:
    app: web
spec:
  containers:
  - name: nodecustom
    image: cabupy/nodecustom
    imagePullPolicy: Never
    command: [ "echo", "SUCCESS" ]
    ports:
      - containerPort: 3000
